export default [
  {
    availableSize: null,
    brand: 'Emzol',
    category: {productCategoryId: 2, productCategoryName: 'Malaria'},
    createDate: '2022-03-26T10:37:55.000000Z',
    description: 'Good for headache',
    discountAvailable: '0',
    discountPercentage: null,
    images: [],
    isFreeDelivery: 'Yes',
    name: 'Vitamin C',
    offerShippingWarranty: 'Yes',
    pharmacistId: 1,
    price: 3000,
    productId: 1,
    quantity: 6,
    specialOffer: null,
    status: 'Review',
    storeId: 1,
    vendor: 'John Doe',
    weight: '100mg',
  },
];
