export default [
  {
    id: 1,
    name: 'Dr. John Doe',
    speciality: 'Cardiologist',
    rating: 2.5,
    location: 'New York, NY',
    price: '$100',
    hours: '9:00AM - 2:00PM',
  },
  {
    id: 2,
    name: 'Dr. Abiola Sadau',
    speciality: 'Dentist',
    rating: 3.5,
    location: 'Lagos, Nigeria',
    price: '$60',
    hours: '10:00AM - 5:00PM',
  },
  {
    id: 3,
    name: 'Dr. Hussain Adebayo',
    speciality: 'Skin Specialist',
    rating: 4.5,
    location: 'Lagos, Nigeria',
    price: '$90',
    hours: '11:00AM - 9:00PM',
  },
  {
    id: 4,
    name: 'Dr. Adebayo',
    speciality: 'Dentist',
    rating: 4,
    location: 'Lagos, Nigeria',
    price: '$100',
    hours: '8:00AM - 8:00PM',
  },
  {
    id: 5,
    name: 'Dr. Martha Emefile',
    speciality: 'Dentist',
    rating: 3.4,
    location: 'Anambra, Nigeria',
    price: '$20',
    hours: '7:00AM - 12:00PM',
  },
  {
    id: 6,
    name: 'Dr. Kate John',
    speciality: 'Dentist',
    rating: 2.4,
    location: 'Ibom, Nigeria',
    price: '$80',
    hours: '2:00PM - 12:00AM',
  },
  {
    id: 7,
    name: 'Dr. Joan Mich',
    speciality: 'Dentist',
    rating: 2.5,
    location: 'PH, Nigeria',
    price: '$60',
    hours: '5:00PM - 02:00AM',
  },
  {
    id: 8,
    name: 'Dr. Henry Slice',
    speciality: 'CardioVascular',
    rating: 4,
    location: 'Abuja, Nigeria',
    price: '$100',
    hours: '4:00AM - 10:00AM',
  },
];
